version: '3.7'
services:
  postgres:
    container_name: postgres-compose
    image: 'postgres:12'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - '/data/postgres:/data/postgres'
    ports:
      - '5432'
    restart: always

  logging:
    container_name: seq-logging-compose
    image: 'datalust/seq:5.1'
    restart: always
    volumes:
      - '/data/seq:/data/seq'
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341'
      - '6100:80'

  configuration:
    container_name: configuration-composer
    image: 'docker.pkg.github.com/fitness-professional-association/configuration.fitness-pro.ru/configuration.fitness-pro.ru:dev'
    ports:
      - '5100:80'
    restart: always
    depends_on:
      - postgres

  lc:
    container_name: lc-composer
    image: 'docker.pkg.github.com/fitness-professional-association/lc.fitness-pro.ru/lc.fitness-pro.ru:1.0.0.0.dev'
    ports:
      - '80'
    restart: always
    depends_on:
      - configuration
