version: '3.7'
services:
  Api:
    container_name: Api-composer
    image: 'docker pull docker.pkg.github.com/fitness-professional-association/api.fitness-pro.ru/api.fitness-pro.ru:dev'
    ports:
      - '5500:5000'
    restart: always

  postgres:
    container_name: postgres-compose
    image: 'postgres:12'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - '/data/postgres:/data/postgres'
    ports:
      - '5432'
    restart: always

  logging:
    container_name: seq-logging-compose
    image: 'datalust/seq:5.1'
    restart: always
    volumes:
      - '/data/seq:/data'
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341'
      - '6100:80'

  configuration:
    container_name: configuration-composer
    image: 'docker.pkg.github.com/fitness-professional-association/configuration.fitness-pro.ru/configuration.fitness-pro.ru:dev'
    ports:
      - '5100:80'
    restart: always
    depends_on:
      - postgres

  lc:
    container_name: lc-composer
    image: 'docker.pkg.github.com/fitness-professional-association/lc.fitness-pro.ru/lc.fitness-pro.ru:dev'
    ports:
      - '5200:80'
    restart: always
    depends_on:
      - configuration

  Crm:
    container_name: Crm-composer
    image: 'docker.pkg.github.com/fitness-professional-association/crm.fitness-pro.ru/crm.fitness-pro.ru:dev'
    ports:
      - '5300:80'
    restart: always
    depends_on:
      - configuration

  Identity:
    container_name: Identity-composer
    image: 'docker.pkg.github.com/fitness-professional-association/identity.fitness-pro.ru/identity.fitness-pro.ru:dev'
    ports:
      - '5400:80'
    restart: always
    
  lcRest:
    container_name: lc-Rest-composer
    image: 'docker.pkg.github.com/fitness-professional-association/fpa.lcrest/fpa.lcrest:dev'
    ports:
      - '5600:80'
    restart: always    
